name := "cloud-hypervisor"
packages := "
cloud-hypervisor
"
version_package := "cloud-hypervisor"
pre_commands := "source /etc/os-release"
external_repos := "https://download.opensuse.org/repositories/home:cloud-hypervisor/Fedora_\\$VERSION_ID/home:cloud-hypervisor.repo"

import '../sysext.just'

all: default
