name := "cloud-hypervisor"
packages := "
cloud-hypervisor
"
version_package := "cloud-hypervisor"
pre_commands := "source /etc/os-release"
external_repos := "https://download.opensuse.org/repositories/home:cloud-hypervisor/Fedora_\\$VERSION_ID/home:cloud-hypervisor.repo"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:43 x86_64,aarch64
"

import '../sysext.just'

all: default
