name := "ghostty"
packages := "
ghostty
"
copr_repos := "scottames/ghostty"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:43 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:44 x86_64,aarch64
"

import '../sysext.just'

all: default
