version = 1

[[annotations]]
path = [
    ".github/docs-templates/body.md",
    ".github/docs-templates/header.md",
    ".github/workflow-templates/**",
    "CONTRIBUTING.md",
    "README.containers.md",
    "README.md",
    "docs/.bundle/config",
    "docs/Gemfile.lock",
    "docs/index.md",
]
SPDX-FileCopyrightText = [
    "Timothée Ravier <tim@siosm.fr>"
]
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  "*/Containerfile",
  "*/README.md",
  "*/justfile",
  "nordvpn-gui/usr/lib/systemd/system/nordvpnd.service.d/librarypath.conf",
  "nordvpn/usr/lib/systemd/system/nordvpnd.service.d/librarypath.conf",
  "tailscale/usr/lib/tmpfiles.d/tailscale.conf",
]
SPDX-FileCopyrightText = [
    "Fedora sysexts contributors"
]
SPDX-License-Identifier = "MIT"
