name := "nordvpn"
packages := "nordvpn"
files := "usr"
upholds := "
nordvpnd.service
nordvpnd.socket
"
pre_commands := "rpm --import https://repo.nordvpn.com/yum/nordvpn/centos/x86_64/repodata/repomd.xml.key && echo -e '[code]\nname=NordVPN\nbaseurl=https://repo.nordvpn.com/yum/nordvpn/centos/x86_64/\nenabled=1\ngpgcheck=1\ngpgkey=https://repo.nordvpn.com/yum/nordvpn/centos/x86_64/repodata/repomd.xml.key' | tee /etc/yum.repos.d/nordvpn.repo > /dev/null"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64
quay.io/fedora-ostree-desktops/base-atomic:43 x86_64
quay.io/fedora-ostree-desktops/base-atomic:44 x86_64
"

import '../sysext.just'

all: default

install-manual:
    #!/bin/bash
    set -euo pipefail
    if [[ -n "{{debug}}" ]]; then
      set -x
    fi

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs

    # Move /var content
    ${SUDO} mv var/lib/nordvpn usr/share
    # Fix permission for tmpfiles config
    ${SUDO} chmod 644 usr/lib/tmpfiles.d/nordvpn.conf
    # Remove service mask
    ${SUDO} rm usr/lib/systemd/system/nordvpn.service
    # nordvpnd links against the unversioned libsqlite3.so soname, but Fedora
    # only ships libsqlite3.so.0.  Since LD_LIBRARY_PATH already includes
    # /usr/lib/nordvpn/, place the shim symlink there so the dynamic linker
    # finds it without any host-side ldconfig changes.
    ${SUDO} ln -sf /lib64/libsqlite3.so.0 usr/lib/nordvpn/libsqlite3.so
