name := "littlesnitch"
packages := "littlesnitch"
upholds := "littlesnitch"

import '../sysext.just'

all: default

# Custom download step to get the RPMs
# TODO: Automate version bumps
download-rpms target arch=arch:
    #!/bin/bash
    set -euo pipefail
    if [[ -n "{{debug}}" ]]; then
      set -x
    fi

    mkdir rpms
    cd rpms

    arch="{{arch}}"
    version="1.0.5-1"
    if [[ "${arch}" == "x86_64" ]]; then
        sha256sum="3b903ccb267aa4e8da1cad1ef22a6aa6c86a4ecf16a8b0e0ab1a00813027d9a7"
    else
        sha256sum="c9577d56fb70132595cd5e80e2404242c58fb668e97d26ba710912274038887c"
    fi

    echo "⬇️ Downloading littlesnitch"
    base_url="https://obdev.at/downloads/littlesnitch-linux"
    if ! curl --location --fail --output "littlesnitch-${version}.${arch}.rpm" \
        "${base_url}/littlesnitch-${version}.${arch}.rpm"; then
        echo "⚠️  Not found in main folder, trying legacy folder"
        curl --location --fail --output "littlesnitch-${version}.${arch}.rpm" \
            "${base_url}/legacy/littlesnitch-${version}.${arch}.rpm"
    fi
    echo "${sha256sum}  littlesnitch-${version}.${arch}.rpm" | sha256sum --check
