name := "youki"

import '../sysext.just'

all: default

# Custom download step to get the binary
# TODO: Automate version bumps
download-manual arch=arch:
    #!/bin/bash
    set -euo pipefail
    if [[ -n "{{debug}}" ]]; then
      set -x
    fi

    mkdir binaries
    cd binaries

    arch="{{arch}}"
    version="0.6.0"
    if [[ "${arch}" == "x86_64" ]]; then
        sha256sum="e920231ee35a157d48e267611a00c9d5f75b60b003818aa571dda04ca9196e59"
    else
        sha256sum="7836712b64aab23ef3ace424abeea8c14bf02ab789d67c47223bca83568176da"
    fi

    echo "⬇️ Downloading youki"
    curl --location --fail --output "youki-${version}-${arch}-gnu.tar.gz" \
        "https://github.com/youki-dev/youki/releases/download/v${version}/youki-${version}-${arch}-gnu.tar.gz"
    echo "${sha256sum}  youki-${version}-${arch}-gnu.tar.gz" | sha256sum --check

    # Version & metadata
    echo "${version}" > ../version
    echo "${sha256sum} youki-${version}-${arch}-gnu.tar.gz" > ../inputs

    tar xf youki-${version}-${arch}-gnu.tar.gz
    rm youki-${version}-${arch}-gnu.tar.gz README.md

# Skip default recipe
version:
    true

# Custom installation step to install the binary
install-manual:
    #!/bin/bash
    set -euo pipefail
    if [[ -n "{{debug}}" ]]; then
      set -x
    fi

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs

    echo "➡️ Installing youki"
    ${SUDO} install -D -m 755 ../binaries/youki   usr/bin/youki
    ${SUDO} install -D -m 644 ../binaries/LICENSE usr/share/licenses/youki/LICENSE

    ${SUDO} chown -R root: usr
