name := "wasmtime"

import '../sysext.just'

all: default

# Custom download step to get wasmtime
# TODO: Automate version bumps
download-manual arch=arch:
    #!/bin/bash
    set -euo pipefail
    if [[ -n "{{debug}}" ]]; then
      set -x
    fi

    mkdir binaries
    cd binaries

    arch="{{arch}}"
    version="43.0.0"
    if [[ "${arch}" == "x86_64" ]]; then
        sha256sum="e75a4933253fbc7b027c670b699490f163e3c86784f1db66581ae80fc0eb652c"
    else
        sha256sum="1cbec3240f7ee7a7d4bd5bc6248e66035f53d31cdb987bca8a57cb129bc539d9"
    fi

    echo "⬇️ Downloading wasmtime"
    destfile="wasmtime-v${version}-${arch}-linux.tar.xz"
    wget "https://github.com/bytecodealliance/wasmtime/releases/download/v${version}/${destfile}"
    echo "${sha256sum}  ${destfile}" | sha256sum -c -
    tar xf "${destfile}"
    mv wasmtime-*/{wasmtime,LICENSE} .

    # Version & metadata
    echo "${version}" > ../version
    echo "${sha256sum}  ${destfile}" > ../inputs

# Skip default recipe
version:
    true

# Custom installation step to install bandwhich
install-manual:
    #!/bin/bash
    set -euo pipefail
    if [[ -n "{{debug}}" ]]; then
      set -x
    fi

    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi

    cd rootfs

    echo "➡️ Installing wasmtime"
    ${SUDO} install -D -m 755 ../binaries/wasmtime usr/bin/wasmtime
    ${SUDO} install -D -m 644 ../binaries/LICENSE usr/share/licenses/wasmtime/LICENSE

    ${SUDO} chown -R root: usr
