name: "Build sysexts: Fedora CoreOS (stable) (aarch64)"

env:
  IMAGE: 'quay.io/fedora/fedora-coreos:stable'
  RELEASE: 'stable'
  NAME: 'Fedora CoreOS (stable)'
  SHORTNAME: 'fedora-coreos'
  GH_TOKEN: ${{ github.token }}
  PR: ${{ github.event_name == 'pull_request' }}
  ARCH: 'aarch64'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * MON'
  workflow_dispatch:

# Needed to allow creating a release
permissions:
  contents: write

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.sysext }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: "ubuntu-24.04-arm"
    container:
      image: "quay.io/fedora/fedora:41"
      options: "--privileged --security-opt label=disable --user 0:0 -v /proc/:/host/proc/:rw"
    steps:
      - name: "Install tools"
        run: |
          dnf install -y \
            cpio \
            dnf5-plugins \
            erofs-utils \
            git \
            jq \
            just \
            podman \
            wget
          dnf config-manager addrepo --from-repofile="https://cli.github.com/packages/rpm/gh-cli.repo"
          dnf install -y gh --repo gh-cli

      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Setup artifacts directory"
        run: |
          mkdir -p artifacts

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Build sysext: kubernetes-cri-o-1.29"
        env:
          SYSEXT: kubernetes-cri-o-1.29
        run: |
          cd "${SYSEXT}"
          if [[ "${PR}" == "true" ]]; then
              diff="$(git diff origin/main HEAD --stat -- . ; git diff origin/main HEAD --stat -- ../sysext.just)"
              if [[ -z "${diff}" ]]; then
                  echo "Skipping: No changes for this sysext in this PR"
                  exit 0
              fi
          fi
          just build ${IMAGE} ${ARCH}
          mv "${SYSEXT}"*".raw" "../artifacts/"

      - name: "Build sysext: kubernetes-cri-o-1.30"
        env:
          SYSEXT: kubernetes-cri-o-1.30
        run: |
          cd "${SYSEXT}"
          if [[ "${PR}" == "true" ]]; then
              diff="$(git diff origin/main HEAD --stat -- . ; git diff origin/main HEAD --stat -- ../sysext.just)"
              if [[ -z "${diff}" ]]; then
                  echo "Skipping: No changes for this sysext in this PR"
                  exit 0
              fi
          fi
          just build ${IMAGE} ${ARCH}
          mv "${SYSEXT}"*".raw" "../artifacts/"

      - name: "Build sysext: kubernetes-cri-o-1.31"
        env:
          SYSEXT: kubernetes-cri-o-1.31
        run: |
          cd "${SYSEXT}"
          if [[ "${PR}" == "true" ]]; then
              diff="$(git diff origin/main HEAD --stat -- . ; git diff origin/main HEAD --stat -- ../sysext.just)"
              if [[ -z "${diff}" ]]; then
                  echo "Skipping: No changes for this sysext in this PR"
                  exit 0
              fi
          fi
          just build ${IMAGE} ${ARCH}
          mv "${SYSEXT}"*".raw" "../artifacts/"

      - name: Create a release with a SHA256SUMS manifest and systemd-sysupdate configs
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          git config --global --add safe.directory "${PWD}"

          cd ./artifacts

          sha256sum *.raw > SHA256SUMS

          arch=""
          if [[ "${ARCH}" != "x86_64" ]]; then
              arch="-${ARCH}"
          fi

          sysexts=()
          for s in $(ls *.raw); do
              s="${s%-*-x86-64.raw}"
              s="${s%-*-aarch64.raw}"
              sed "s/%%SYSEXT%%/${s}/g" ../.workflow-templates/systemd-sysupdate.conf > ${s}.conf
              if [[ "${SHORTNAME}" == "fedora-coreos" ]]; then
                  sed -i "s/%w/stable${arch}/" ${s}.conf
              fi
          done

          gh release delete \
            --cleanup-tag \
            --yes \
            "${SHORTNAME}-${RELEASE}${arch}" \
            || true

          latest=false
          if [[ "${SHORTNAME}" == "fedora-coreos" ]]; then
            latest="true"
          fi
          gh release create \
            --title "${NAME} sysexts (${ARCH})" \
            --notes "System extensions for ${NAME} (${ARCH})" \
            "${SHORTNAME}-${RELEASE}${arch}" \
            --latest=${latest} \
            ./*
